/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionBiblioteca.h"


void
gestion_biblioteca_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	datos_persona  registrarpersona_1_arg;
	datos_persona  *result_2;
	char  consultarpersona_1_arg;
	bool_t  *result_3;
	datos_prestamo  prestarlibro_1_arg;
	datos_prestamo  *result_4;
	char * devolverlibro_1_arg;
	libro  *result_5;
	char * consultarlibro_1_arg;
	datos_credencial  *result_6;
	datos_credencial  abrir_sesion_1_arg;
	bool_t  *result_7;
	int  verificar_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_biblioteca, gestion_biblioteca_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = registrarpersona_1(&registrarpersona_1_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = consultarpersona_1(&consultarpersona_1_arg, clnt);
	if (result_2 == (datos_persona *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = prestarlibro_1(&prestarlibro_1_arg, clnt);
	if (result_3 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = devolverlibro_1(&devolverlibro_1_arg, clnt);
	if (result_4 == (datos_prestamo *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = consultarlibro_1(&consultarlibro_1_arg, clnt);
	if (result_5 == (libro *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = abrir_sesion_1(&abrir_sesion_1_arg, clnt);
	if (result_6 == (datos_credencial *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = verificar_1(&verificar_1_arg, clnt);
	if (result_7 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_biblioteca_1 (host);
exit (0);
}
