/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionBiblioteca.h"
#include <rpc/types.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int validar(int dia, int mes, int anio);
int val;

void
gestion_biblioteca_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	datos_persona  objPersona;
	datos_persona  *result_2;
	char  consultarpersona_1_arg;
	bool_t  *result_3;
	datos_prestamo  objPrestamo;
	datos_prestamo  *result_4;
	char  devolverlibro_1_arg[20];
	libro  *result_5;
	libro  objLibro;
	datos_credencial  *result_6;
	datos_credencial  abrir_sesion_1_arg;
	bool_t  *result_7;
	int  verificar_1_arg;
	char *consult;
	char *pedir;

#ifndef	DEBUG
	clnt = clnt_create (host, gestion_biblioteca, gestion_biblioteca_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	char username[20];
	char clave[20];

	int op =0;

	do{
		result_2 = (datos_persona *)malloc(7 * sizeof(datos_persona));
		result_6 = (datos_credencial*)malloc(1* sizeof(datos_credencial));
		result_5 = (libro *)malloc(4 * sizeof(libro));
		consult=(char*)malloc(sizeof(char)*20);
		pedir=(char*)malloc(sizeof(char)*20);
		printf("===== Menú Inicio =====\n");
		printf("*  1.Abrir Sesion     *\n");
		printf("*  2.Salir  	      *\n");
		printf("=======================\n");
		printf("\n  Ingrese la opcion: ");
		scanf("%d", &op);
		switch(op){
			case 1:
				printf("\nIngrese el username: ");
				scanf("%s", username);
				printf("\nIngrese la clave: ");
				scanf("%s", clave);
				if (strcmp(username, "admin") == 0 && strcmp(clave, "1234") == 0) {
					strcpy(result_6->usuario, "admin");
					strcpy(result_6->clave, "1234");
					strcpy(result_6->ocupacion, "admin");
				} else {
					strcpy(abrir_sesion_1_arg.usuario, username);
					strcpy(abrir_sesion_1_arg.clave, clave);
					result_6 = abrir_sesion_1(&abrir_sesion_1_arg, clnt);
				}
				if (result_6 != (datos_credencial *)NULL) {
					int validarCod;
					printf("\n Numero de verificacion: %d", result_6->id);
					printf("\n Ingrese el codigo de verificacion: ");
					scanf("%d",&validarCod);
					if (result_6->id == validarCod ) {
					do {
						printf("\n============  Menú Admin  =============\n");
						printf("*  1. Registrar Profesor o Estudiante *\n");
						printf("*  2. Devolver Libro		      *\n");
						printf("*  3. Salir               	      *\n");
						printf("=======================================\n");
						printf("\n  Ingrese la opcion: ");
						scanf("%d", &op);
						switch (op) {
						case 1:
							printf("\nIngrese el nombre: ");
							scanf("%s", objPersona.nombre);
							printf("\nIngrese el Apellido: ");
							scanf("%s", objPersona.apellido);
							printf("\nIngrese el telefono: ");
							scanf("%s", objPersona.telefono);
							printf("\nIngrese la ocupacion: ");
							scanf("%s", objPersona.ocupacion);
							printf("\nIngrese el codigo: ");
							scanf("%s", objPersona.codigo);
							result_1 = registrarpersona_1(&objPersona, clnt);
							if (result_1 == (bool_t *)NULL) {
								clnt_perror(clnt, "call failed");
							} else {
								printf("\n Se ha registrado el %s con exito \n", objPersona.ocupacion);
							}
						break;

						case 2:
							memset(result_4, 0, 0);
							printf("\n Ingrese el codigo de la persona a consultar el prestamo: ");
							scanf("%s", consult);
							result_4 = devolverlibro_1(&consult, clnt);
							if (result_4 == (datos_prestamo *) NULL) {
								clnt_perror (clnt, "call failed");
							}
							 if ((*result_4).multa == -1) {
								printf("Persona NO encontrada \n");
							} else {
								printf("\nIngrese la fecha en la que se devolvio el libro: ");
								printf("\nDia: ");
								scanf("%d", &objPrestamo.dia_3);
								printf("\nMes: ");
								scanf("%d", &objPrestamo.mes_3);
								printf("\nAño: ");
								scanf("%d", &objPrestamo.anio3);
								val = validar(objPrestamo.dia_3,objPrestamo.mes_3,objPrestamo.anio3);
								while(val!=1){
									if(!validar(objPrestamo.dia_3,objPrestamo.mes_3,objPrestamo.anio3)){
										printf("\nIngrese la fecha en la que se devolvio el libro: ");
										printf("\nDia: ");
										scanf("%d", &objPrestamo.dia_3);
										printf("\nMes: ");
										scanf("%d", &objPrestamo.mes_3);
										printf("\nAño: ");
										scanf("%d", &objPrestamo.anio3);
									}
								}
								int dia1 = ((result_4->anio2*365)+(result_4->mes_2-1)*30+result_4->dia_2);
								int dia2 = ((objPrestamo.anio3*365)+(objPrestamo.mes_3-1)*30+objPrestamo.dia_3);
								int multa = dia2-dia1;
								if(multa > 0){
									if(multa >=1 && multa <=3){
										multa = 10000;
										printf("\n La multa a cancelar es: %d\n", multa);
									}
									else if(multa >=4 && multa <=8){
										multa = 10000+(1000*(multa-3));
										printf("\n La multa a cancelar es: %d\n", multa);
									}
									else if(multa >8){
										multa = 10000+(2000*(multa-8));
										printf("\n La multa a cancelar es: %d\n", multa);
									}
								}
								else{
									printf("\n No hay multa a cancelar ");
								}
							}
						break;	
						}
					
					} while (op != 3);
				}
					else if(strcmp(result_2->ocupacion, "estudiante")){
						int vali;
						strcpy(result_2->nombre, username);
						strcpy(result_2->codigo, clave);
						result_2 = consultarpersona_1(&consultarpersona_1_arg, clnt);
						printf("\nEl numero de verificacion es: %d\n", result_2->id);
						printf("\nIngrese el codigo de verificacion: ");
						scanf("%d",&vali);
						result_7 = verificar_1(&vali, clnt);
						if (result_7 == (bool_t *) NULL) {
							clnt_perror (clnt, "call failed");
						}
						else if(result_7 == TRUE){
							do{
								printf("======== Menú Biblioteca=========\n");
								printf("*  1. Consultar Libro           *\n");
								printf("*  2. Pedir Libro               *\n");
								printf("*  3. Salir                     *\n");
								printf("=================================\n");
								printf("\n  Ingrese la opcion: ");
								scanf("%d", &op);
								switch(op){
									
									case 1:
										do{
											printf("======== Menú Consulta  =========\n");
											printf("*  1. Consultar por categoria   *\n");
											printf("*  2. Consultar por autor       *\n");
											printf("*  3. Consultar por editorial   *\n");
											printf("*  4. Salir                     *\n");
											printf("================================\n");
											printf("\n  Ingrese la opcion: ");
											scanf("%d", &op);
											switch(op){
												case 1:
													printf("\nIngrese la categoria a consultar: ");
													scanf("%s", consult);
													result_5 = consultarlibro_1(&consult, clnt);
													if (result_5 == (libro *) NULL) {
														clnt_perror (clnt, "call failed");
													}
													else if((result_5->error)== -1){
														printf("\n La categoria no existe\n");
													}
													else{
														printf("\nNombre: %s", (*result_5).nombre);
														printf("\nAutor: %s", (*result_5).autor);
														printf("\nIsbn: %s", (*result_5).isbn);
														printf("\nEditorial: %s\n", (*result_5).editorial);
													}
												break;
												
												case 2:
													printf("\nIngrese el autor a consultar: ");
													scanf("%s", consult);
													result_5 = consultarlibro_1(&consult, clnt);
													if (result_5 == (libro *) NULL) {
														clnt_perror (clnt, "call failed");
													}
													else if((result_5->error)== -1){
														printf("\n El autor no existe\n");
													}
													else{
														printf("\nNombre: %s", (*result_5).nombre);
														printf("\nAutor: %s", (*result_5).autor);
														printf("\nIsbn: %s", (*result_5).isbn);
														printf("\nEditorial: %s\n", (*result_5).editorial);
													}
												break;

												case 3:
													printf("\nIngrese la editorial a consultar: ");
													scanf("%s", consult);
													result_5 = consultarlibro_1(&consult, clnt);
													if (result_5 == (libro *) NULL) {
														clnt_perror (clnt, "call failed");
													}
													else if((result_5->error)== -1){
														printf("\n La editorial no existe\n");
													}
													else{
														printf("\nNombre: %s", (*result_5).nombre);
														printf("\nIsbn: %s", (*result_5).isbn);
														printf("\nArea de conocimiento: %s", (*result_5).area_conocimiento);
														printf("\nAutor: %s\n", (*result_5).autor);
													}
												break;
											}
										}while(op!=4);
									break;
								
									case 2:

											printf("\n Ingrese nombre del libro a pedir: ");
											scanf("%s", objPrestamo.nom_libro);
											strcpy(objPrestamo.nom_libro, consult);
											result_5 = consultarlibro_1(&consult, clnt);
											printf("\n Ingrese codigo del estudiante: ");
											scanf("%s", objPrestamo.codigo);
											printf("\n Fecha Prestamo : ");
											printf("\n Dia : ");
											scanf("%d",&objPrestamo.dia_1);
											printf("\n Mes : ");
											scanf("%d", &objPrestamo.mes_1);
											printf("\n Año : ");
											scanf("%d",&objPrestamo.anio1);
											val = validar(objPrestamo.dia_1, objPrestamo.mes_1, objPrestamo.anio1);
											while(val !=1){
											if(!validar(objPrestamo.dia_1, objPrestamo.mes_1, objPrestamo.anio1)){
												printf("\n Fecha Prestamo : ");
												printf("\n Dia : ");
												scanf("%d",&objPrestamo.dia_1);
												printf("\n Mes : ");
												scanf("%d", &objPrestamo.mes_1);
												printf("\n Año : ");
												scanf("%d",&objPrestamo.anio1);
												}
											}
											printf("\n Fecha devolucion : ");
											printf("\n Dia : ");
											scanf("%d",&objPrestamo.dia_2);
											printf("\n Mes : ");
											scanf("%d", &objPrestamo.mes_2);
											printf("\n Año : ");
											scanf("%d",&objPrestamo.anio2);
											val =validar(objPrestamo.dia_2, objPrestamo.mes_2, objPrestamo.anio2);
											while(val!=1){
												if(!validar(objPrestamo.dia_2, objPrestamo.mes_2, objPrestamo.anio2)){
													printf("\n Fecha devolucion : ");
												printf("\n Dia : ");
												scanf("%d",&objPrestamo.dia_2);
												printf("\n Mes : ");
												scanf("%d", &objPrestamo.mes_2);
												printf("\n Año : ");
												scanf("%d",&objPrestamo.anio2);
												}
											}
											objPrestamo.anio3 =0;
											objPrestamo.dia_3=0;
											objPrestamo.mes_3 =0;
											result_3 = prestarlibro_1(&objPrestamo, clnt);
											if (result_3 == (bool_t *) NULL) {
												clnt_perror (clnt, "call failed");
											}
											else if(result_3 == FALSE){
												printf("\n No se pudo prestar el libro\n");
											}
											else {
												printf("\n Se presto el libro\n");
											}
									break;
								}
							}while(op!=3);
						}
					}
				}
			break;

			case 2:
				printf("\n Hasta luego!!!");
				break;
		}
	}while(op!=2);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	gestion_biblioteca_1 (host);
exit (0);
}

int validar(int dia, int mes, int anio){
	 int dia_maximo,fecha_correcta;

    fecha_correcta = 0;

    if ( mes >= 1 && mes <= 12 )
    {
        switch ( mes )
        {
            case  1 :
            case  3 :
            case  5 :
            case  7 :
            case  8 :
            case 10 :
            case 12 : dia_maximo = 31;
                      break;

            case  4 :
            case  6 :
            case  9 :
            case 11 : dia_maximo = 30;
                      break;

            case  2 : if ( anio % 4 == 0 && anio % 100 != 0 || anio % 400 == 0 )
                          dia_maximo = 29;
                      else
                          dia_maximo = 28;
        }

        if ( dia >= 1 && dia <= dia_maximo )
            fecha_correcta = 1;
    }

    if ( fecha_correcta )
        printf( "\n   FECHA CORRECTA" );
    else
        printf( "\n   FECHA INCORRECTA" );


    return fecha_correcta;

}
