/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gestionBiblioteca.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
gestion_biblioteca_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		datos_persona registrarpersona_1_arg;
		char consultarpersona_1_arg;
		datos_prestamo prestarlibro_1_arg;
		char *devolverlibro_1_arg;
		char *consultarlibro_1_arg;
		datos_credencial abrir_sesion_1_arg;
		int verificar_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case registrarPersona:
		_xdr_argument = (xdrproc_t) xdr_datos_persona;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) registrarpersona_1_svc;
		break;

	case consultarPersona:
		_xdr_argument = (xdrproc_t) xdr_char;
		_xdr_result = (xdrproc_t) xdr_datos_persona;
		local = (char *(*)(char *, struct svc_req *)) consultarpersona_1_svc;
		break;

	case prestarLibro:
		_xdr_argument = (xdrproc_t) xdr_datos_prestamo;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) prestarlibro_1_svc;
		break;

	case devolverLibro:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_datos_prestamo;
		local = (char *(*)(char *, struct svc_req *)) devolverlibro_1_svc;
		break;

	case consultarLibro:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_libro;
		local = (char *(*)(char *, struct svc_req *)) consultarlibro_1_svc;
		break;

	case abrir_sesion:
		_xdr_argument = (xdrproc_t) xdr_datos_credencial;
		_xdr_result = (xdrproc_t) xdr_datos_credencial;
		local = (char *(*)(char *, struct svc_req *)) abrir_sesion_1_svc;
		break;

	case verificar:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) verificar_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (gestion_biblioteca, gestion_biblioteca_version);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, gestion_biblioteca, gestion_biblioteca_version, gestion_biblioteca_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (gestion_biblioteca, gestion_biblioteca_version, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, gestion_biblioteca, gestion_biblioteca_version, gestion_biblioteca_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (gestion_biblioteca, gestion_biblioteca_version, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
