/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gestionBiblioteca.h"

bool_t
xdr_datos_persona (XDR *xdrs, datos_persona *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombre, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->apellido, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->telefono, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ocupacion, MAXDAT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->codigo, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datos_prestamo (XDR *xdrs, datos_prestamo *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->nom_libro, MAXDAT,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->codigo, MAXNOM,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 10 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->dia_1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mes_1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->anio1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->dia_2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mes_2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->anio2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->multa))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->dia_3))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mes_3))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->anio3))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->dia_1);
			IXDR_PUT_LONG(buf, objp->mes_1);
			IXDR_PUT_LONG(buf, objp->anio1);
			IXDR_PUT_LONG(buf, objp->dia_2);
			IXDR_PUT_LONG(buf, objp->mes_2);
			IXDR_PUT_LONG(buf, objp->anio2);
			IXDR_PUT_LONG(buf, objp->multa);
			IXDR_PUT_LONG(buf, objp->dia_3);
			IXDR_PUT_LONG(buf, objp->mes_3);
			IXDR_PUT_LONG(buf, objp->anio3);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->nom_libro, MAXDAT,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->codigo, MAXNOM,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 10 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->dia_1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mes_1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->anio1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->dia_2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mes_2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->anio2))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->multa))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->dia_3))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mes_3))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->anio3))
				 return FALSE;
		} else {
			objp->dia_1 = IXDR_GET_LONG(buf);
			objp->mes_1 = IXDR_GET_LONG(buf);
			objp->anio1 = IXDR_GET_LONG(buf);
			objp->dia_2 = IXDR_GET_LONG(buf);
			objp->mes_2 = IXDR_GET_LONG(buf);
			objp->anio2 = IXDR_GET_LONG(buf);
			objp->multa = IXDR_GET_LONG(buf);
			objp->dia_3 = IXDR_GET_LONG(buf);
			objp->mes_3 = IXDR_GET_LONG(buf);
			objp->anio3 = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->nom_libro, MAXDAT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->codigo, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dia_1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mes_1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->anio1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dia_2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mes_2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->anio2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->multa))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dia_3))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mes_3))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->anio3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_libro (XDR *xdrs, libro *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->isbn, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->autor, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombre, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->editorial, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->area_conocimiento, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->error))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datos_credencial (XDR *xdrs, datos_credencial *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->usuario, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->clave, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ocupacion, MAXDAT,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
