/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionBiblioteca.h"

bool_t *
registrarpersona_1_svc(datos_persona *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

datos_persona *
consultarpersona_1_svc(char *argp, struct svc_req *rqstp)
{
	static datos_persona  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
prestarlibro_1_svc(datos_prestamo *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

datos_prestamo *
devolverlibro_1_svc(char **argp, struct svc_req *rqstp)
{
	static datos_prestamo  result;

	/*
	 * insert server code here
	 */

	return &result;
}

libro *
consultarlibro_1_svc(char **argp, struct svc_req *rqstp)
{
	static libro  result;

	/*
	 * insert server code here
	 */

	return &result;
}

datos_credencial *
abrir_sesion_1_svc(datos_credencial *argp, struct svc_req *rqstp)
{
	static datos_credencial  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
verificar_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}
